version: '2.1'

services:
  mysql:
    image: docker.io/bitnami/mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - './mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MYSQL_ROOT_PASSWORD=my_password
      - MYSQL_USER=tower
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=tower
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
